config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, :clientes, only: [:show] do
    resources :jobs
    resources :job_apps
  end
  resources :clientes, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job_app.rb
class JobApp < ApplicationRecord
    belongs_to :job
    belongs_to :trabajador, class_name: "Trabajador", foreign_key: :user_id

    time_range = Time.now..(Time.now.midnight + 30.day)
    scope :current , -> { joins(:job).where("jobs.start_datetime > ?", DateTime.now) }
end

app/controllers/job_apps_controller.rb
class JobAppsController < ApplicationController

   # before_action :user_permition!, only: [:new, :index]
    def new
        @user = current_user
        @jobapp = JobApp.new

    end

    def index
        if client_logged_in?
            @jobs = current_client.jobs

        elsif worker_logged_in?
            @worker = Trabajador.find(params[:user_id])
            @jobapps = @worker.job_apps
        else
            @jobapps = current_hro.job_apps.current
        end
    end

    def create
        job = Job.find(params[:job_id])
        current_worker.jobs << job
        redirect_to user_job_apps_path(current_worker.id)
    end

    def update
        jobapp = JobApp.find(params[:job_app_id])
        jobapp.update(approved: true)
        redirect_to user_job_apps_path(current_hro.id)
    end

    def destroy
        jobapp = JobApp.find(params[:job_app_id])
        jobapp.destroy
        redirect_to user_job_apps_path(current_hro.id)
    end

end

app/views/job_apps/index.html.erb
<div class="container-fluid">
      <div class="row">

  <nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link" href='<%=user_path(current_user.id)%>'>
            <span data-feather="home"></span>
            Dashboard <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="<%= user_job_apps_path(current_user.id) %>">
            <span data-feather="file"></span>
            <% if client_logged_in? %>
              Approved applicants
            <% else %>
            Job Apps
            <% end %>
          </a>
        </li>
        <% if client_logged_in? || hro_logged_in? %>
        <li class="nav-item">
          <a class="nav-link" href="<%= user_jobs_path(current_user.id)%>">
            <span data-feather="folder"></span>
              Jobs
          </a>
        </li>
        <% end %>
        <% if hro_logged_in? %>
          <li class="nav-item">
            <a class="nav-link" href="<%= clientes_path(current_hro.id) %>">
              <span data-feather="users"></span>
              Clients
            </a>
          </li>
        <%end%>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <span data-feather="bar-chart-2"></span>
            Reports
          </a>
        </li>
      </ul>
    </div>
  </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <% if client_logged_in? %>
              <h1 class="h2">Approved Applicants</h1>
            <% else %>
              <h1 class="h2">Job Applications</h1>
            <% end %>
            
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                This week
              </button>
            </div>
          </div>
          <div>

      </div>
        <% if current_user && current_user.role == "Trabajador"%>


          <div id="accordion">

            <table class="table ">
            <thead>
              <tr class = 'row'>

                <th class="col-sm-3" style="padding-left: 46px;">Position:</th>
                <th class="col-sm-3" style="padding-left: 2rem;">Client:</th>
                <th class="col-sm-2" style="padding-left: 0.75rem;">Start Date:</th>
                <th class="col-sm-2" style="padding-left: 0px;">End Date:</th>
                <th class="col-sm-2" style="padding-left: 2.75rem;">Status:</th>

              </tr>
              
            </thead>
            </table>
            <%if @jobapps.length == 0%>
            <h2 class = 'mt-5'>U have no applied to any job or have not been selected!</h2>
            <% end %>

    <% @jobapps.each do |ja|%>
      <div class="card">
        <div class="card-header" id="heading<%= ja.job.id %>">

            <button class="btn btn-link w-100" data-toggle="collapse" data-target="#collapse<%= ja.job.id %>" aria-expanded="false" aria-controls="collapse<%= ja.job.id %>">

                <div class="row">
                  <div class="col-sm-3 text-left" ><%= ja.job.position%> </div>
                  <div class="col-sm-3 text-left" ><%= ja.job.cliente.name%> <%= ja.job.cliente.last_name%> </div>
                  <div class="col-sm-2 text-left"><strong></strong> <%= ja.job.start_datetime&.strftime('%b %e, %l:%M %p')%></div>
                  <div class="col-sm-2 text-left"><strong></strong> <%= ja.job.end_datetime&.strftime('%b %e, %l:%M %p')%></div>
                  
                  <% if ja.approved == true %>
                    <div class="quantity-good col-sm-2 text-center"><strong>
                    Approved</strong></div>
                  <% else %>
                  <div class="quantity-reg col-sm-2 text-center"><strong>
                  Pending</strong></div>
                  <% end %>
                </div>

            </button>
        </div>

        <div id="collapse<%= ja.job.id %>" class="collapse" aria-labelledby="heading<%= ja.job.id %>" data-parent="#accordion">
          <div class="card-body">
            <div>
              <strong>Description: </strong> <%= ja.job.description%>
            </div>
            <div>
              <strong>Requirements: </strong><%= ja.job.requirements%>
            </div>
            <div>
              <strong>Salary: </strong><%= ja.job.salary%>
            </div>
          </div>
        </div>
      </div>
    <% end %>

</div>
  <% end %>
<% # HRO VIEW JOB_APPS%>
        <% if hro_logged_in?%>
        <table class = 'table table-hover'>
          <thead class = 'thead-light'>
            <tr>
              <th>Name</th>
              <th>Last Name</th>
              <th>Phone</th>
              <th>Rating</th>
              <th>Position</th>
              <th>Starting Date</th>
              <th>Client</th>
              <th>Approve</th>
            </tr>
          </thead>

            <tbody>
              <% @jobapps.each do |ja| %>
                <% if ja.approved == true %>
                <tr class = 'table-success'>
                <%else%>
                <tr class = 'table-warning'>
                <% end %>
                  <td><%= ja.trabajador.name%></td>
                  <td><%= ja.trabajador.last_name%></td>
                  <td><%= ja.trabajador.phone%></td>
                  <td><% ja.trabajador.rating.to_i.times do  %>
                    <span class="glyphicon glyphicon-star"></span>
                    <% end %>
                    <% ja.trabajador.blank_stars.to_i.times do  %>
                    <span class="glyphicon glyphicon-star-empty"></span>
                    <% end %></td>
                  <td><%= ja.job.position %></td>
                  <td><%= ja.job.start_datetime&.strftime('%b %e, %l:%M %p') %></td>
                  <td><%= ja.job.cliente.name %> <%=ja.job.cliente.last_name %></td>
                  
                  <td><div class = 'row botones '><% if ja.approved == nil %>
                    <%=button_to user_job_app_path(ja.user_id, ja.id), method: :patch, params: {job_app_id: ja.id}, class: "btn btn-primary btn-sm glyphicon glyphicon-ok" do %>
                    <% end %>
                  <% end%>
                  <% if ja.approved == nil||ja.approved == true %>
                    <%=button_to user_job_app_path(ja.user_id, ja.id), method: :delete, params: {job_app_id: ja.id}, class: "btn btn-danger btn-sm glyphicon glyphicon-remove" do %>
                    <% end %>
                  <% end%></div></td>
                  
                </tr>
              <% end %>

        <%end%>
        <% if client_logged_in?%>
        
            <div>
                <% @jobs.each do |j|%>
                <h4><%= j.position%></h4>
                <%= j.start_datetime&.strftime('%b %e, %l:%M %p')%>
                <ul>
                <div class="container-fluid">
                  <div class="row flex-row-jobapps flex-nowrap">

                
                  <% j.job_apps.where(approved: true).each do |ja|%>
                  <div class="col-xs-3 bordered-card">
                    <div class="well"><%= image_tag(ja.trabajador.avatar,size: '150x170')%></div>
                    <p>
                    <div class = 'content-card'><strong><%= ja.trabajador.name %> <%= ja.trabajador.last_name %></strong><hr/>
                    <br>
                    <strong>Cel: </strong><%= ja.trabajador.phone %>
                    <br>
                    <strong>Email: </strong><%= ja.trabajador.email %>
                    </div>
                   
                    </p>

                  </div>
          
                    <% end %>
                    
              </div>
                </div>
                    <hr>
                </ul>
                  <% end %>
            </div>
        
        <%end%>
        


          </main>
    </div>


<!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>


    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

app/views/job_apps/new.html.erb
new job_app

<% @worker.job_apps.each do |ja|%>
<%= ja.approved %>
<% end %>