config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, :clientes, only: [:show] do
    resources :jobs
    resources :job_apps
  end
  resources :clientes, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
    belongs_to :cliente, foreign_key: :user_id, class_name: "Cliente"
    has_many :job_apps
end  

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

    #before_action :user_permition!, only: [:create, :new]
    protect_from_forgery with: :exception

    def index
        if client_logged_in?
            @client = Cliente.find(params[:user_id] || params[:cliente_id])
            @jobs = @client.jobs
        elsif hro_logged_in?
            @jobs = Job.joins(:cliente).where(:users => {:HRO_id => current_hro.id}).order(start_datetime: :desc)
        else
            @client = Cliente.all
            @jobs = Job.all
        end
    end

    def show
        @client = Cliente.find(params[:user_id])
        @job = @client.jobs.find(params[:id])#.order(start_datetime: :desc)[0...5]

        if worker_logged_in?
            respond_to do |format|
                format.js {render 'showInfo', layout: false} # Add this line to you respond_to block
            end
        end
  
    end

    def new
        @user = Cliente.find(current_client.id)
        @job = Job.new
    end

    def create
        @user = Cliente.find(current_user.id)
        @user.jobs.create(post_params)
        redirect_to cliente_jobs_path(current_client.id)
    end

    private
    def post_params
        params.require(:job).permit(:user_id, :position, :description, :requirements, :start_datetime, :end_datetime, :salary, :quantity)
    end



end

app/views/jobs/_info.html.erb
      <div class="row">


        <main role="main" class="col-md-12 ml-sm-auto col-lg-12 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h4"><%= job.position + ' ' %>details</h1>
    
          </div>
          <div>
      <div><h5>Client: <%= @client.name + ' ' + @client.last_name%></h5></div>
      <strong>Description: </strong><%= job.description%>
      <div>
      <strong>Requirements: </strong><%= job.requirements%>
      </div>
      </div>
      <% if current_user && current_user.role == "Trabajador" && job.job_apps.where(user_id: current_worker.id).length == 0%>
            <div>
                <%=button_to "Apply", user_job_apps_path(current_user), method: :post, params: {job_id: job.id}, class: "btn btn-primary mt-3" %>
            </div>
      <%elsif current_user && current_user.role == "Trabajador" %>
      <br>
      <hr/>
        <div><h5>You have already applied to this job.</h5></div>
      <% end %>
          </main>



<!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>


    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

app/views/jobs/index.html.erb
<div class="container-fluid">
      <div class="row">

  <nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link" href='<%=user_path(current_user.id)%>'>
            <span data-feather="home"></span>
            Dashboard <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= user_job_apps_path(current_user.id) %>">
            <span data-feather="file"></span>
            <% if client_logged_in? %>
              Approved applicants
            <% else %>
              Job Apps
            <% end %>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="<%= user_jobs_path(current_user.id)%>">
            <span data-feather="folder"></span>
            Jobs
          </a>
        </li>
        <% if hro_logged_in? %>
          <li class="nav-item">
            <a class="nav-link" href="<%= clientes_path(current_hro.id)%>">
              <span data-feather="users"></span>
              Clients
            </a>
          </li>
        <%end%>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <span data-feather="bar-chart-2"></span>
            Reports
          </a>
        </li>
      </ul>
    </div>
  </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <%if client_logged_in? %>
              <h1 class="h2">
              <%= @client.name + ' ' + @client.last_name + ' ' %>Jobs</h1>
            <% elsif worker_logged_in? %>
              <h1 class="h2">Available Jobs</h1>
            <% else %>
              <h1 class="h2">Clients' needs</h1>
            <% end %>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                This week
              </button>
            </div>
          </div>
          <% if client_logged_in? %>
              <%= link_to('Create a job', new_user_job_path(current_client.id))%>
            <% end %>
          <% if worker_logged_in? || client_logged_in? %>
            
              <% @jobs.each do |j|%>
                <div class= 'job-box col-md-6'>
                <% q=0 %>
                <% j.job_apps.each do |ja|%>
                  <% q += 1 if ja.approved == true %>
                <% end %>
                <h5><%= link_to("#{j.position + ' ('+ q.to_s + '/' + j.quantity.to_s + ')' }", user_job_path(j.user_id,j.id)) %></h5>
                <ul>
                <li><strong>Start date: </strong> <%=j.start_datetime.strftime('%b %e, %l:%M %p')%>
                <li><strong>Salary: </strong> $<%=j.salary%>
                <li><strong>Requirements: </strong> <%=j.requirements%>
                <div class="progress">
                  <div class="progress-bar progress-bar-success progress-bar-striped active" style="width:<%=(q/j.quantity.to_f)*100%>%;">
              <%=((q/j.quantity.to_f)*100).to_i%>%
                  </div>
                </div>
                </ul>
                </div>
                
              <% end %>
            
          <% end %>
            
            <% if hro_logged_in?%>
              <div id="accordion">

                <table class="table ">
                <thead>
                  <tr class = 'row'>

                    <th class="col-sm-3" style="padding-left: 46px;">Position:</th>
                    <th class="col-sm-4" style="padding-left: 2rem;">Client:</th>
                    <th class="col-sm-2" style="padding-left: 0.75rem;">Start Date:</th>
                    <th class="col-sm-2" style="padding-left: 0px;">End Date:</th>
                    <th class="col-sm-1">Success:</th>

                  </tr>
                  
                </thead>
                </table>
                <%if @jobs.length == 0%>
                <h2 class = 'mt-5'>Go for a walk or grab some coffee, job is done!</h2>
                <% end %>
                  <% @jobs.each do |job|%>
                    <div class="card">
                      <div class="card-header" id="heading<%= job.id %>">

                          <button class="btn btn-link w-100" data-toggle="collapse" data-target="#collapse<%= job.id %>" aria-expanded="false" aria-controls="collapse<%= job.id %>">

                              <div class="row">
                                <div class="col-sm-3 text-left" ><%= job.position%> </div>
                                <div class="col-sm-4 text-left" ><%= job.cliente.name%> <%= job.cliente.last_name%> </div>
                                <div class="col-sm-2 text-left"><strong></strong> <%= job.start_datetime&.strftime('%b %e, %l:%M %p')%></div>
                                <div class="col-sm-2 text-left"><strong></strong> <%= job.end_datetime&.strftime('%b %e, %l:%M %p')%></div>
                                <% if success_rate(job)>=80 %>
                                  <div class="quantity-good col-sm-1 text-right">
                                <% elsif(success_rate(job)<80 && success_rate(job)>50) %>
                                  <div class="quantity-reg col-sm-1 text-right">
                                <% else %>
                                  <div class="quantity col-sm-1 text-right">
                                <% end %>
                                <strong><%= success_rate(job)%>%</strong></div>
                              </div>

                          </button>
                      </div>

                      <div id="collapse<%= job.id %>" class="collapse" aria-labelledby="heading<%= job.id %>" data-parent="#accordion">
                        <div class="row flex-row-jobapps flex-nowrap">

                
                  <% job.job_apps.where(approved: true).each do |ja|%>
                  <div class="col-xs-3 bordered-card">
                    <div class="well"><%= image_tag(ja.trabajador.avatar,size: '150x170')%></div>
                    <p>
                    <div class = 'content-card'><strong><%= ja.trabajador.name %> <%= ja.trabajador.last_name %></strong><hr/>
                    <br>
                    <strong>Cel: </strong><%= ja.trabajador.phone %>
                    <br>
                    <strong>Email: </strong><%= ja.trabajador.email %>
                    </div>
                   
                    </p>

                  </div>
          
                    <% end %>
                    
              </div>
                      </div>
                    </div>
                  <% end %>

              </div>              
            <% end %>
          </main>
    </div>


<!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>


    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

app/views/jobs/new.html.erb
<div class="container-fluid">
      <div class="row">

  <nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link" href='<%=user_path(current_user.id)%>'>
            <span data-feather="home"></span>
            Dashboard <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= user_job_apps_path(current_user.id) %>">
            <span data-feather="file"></span>
            Job Apps
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="<%= user_jobs_path(current_user.id)%>">
            <span data-feather="folder"></span>
            Jobs
          </a>
        </li>
        <% if hro_logged_in? %>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Customers
            </a>
          </li>
        <%end%>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <span data-feather="bar-chart-2"></span>
            Reports
          </a>
        </li>
      </ul>
    </div>
  </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
         
          <div class = 'container col-sm-6'>
            <%= bootstrap_form_for [@user, @job] do |f| %>
              <%= f.text_field :position, required: true %>
              <%= f.text_area :description %>
              <%= f.text_area :requirements, required: true %>
              <div class = 'd-flex flex-row wrap justify-content-between'>
              <%= f.number_field :salary, prepend: "$" %>
              <%= f.number_field :quantity, required: true %>
              </div>
              <%=f.datetime_select :start_datetime, required: true, class: "form-control"%>
              <%=f.datetime_select :end_datetime, required: true, class: "form-control"%>

              <%= f.submit "Create Job" %>
            <% end %>
            </div>
          </main>
    </div>


<!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>


    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>


    <!-- FORMS -->
 

app/views/jobs/show.html.erb
<div class="container-fluid">
      <div class="row">

    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
              <% if worker_logged_in? %>
                <a class="nav-link active" href='<%=user_path(current_user.id)%>'>
              <% else %>
                <a class="nav-link" href='<%=user_path(current_user.id)%>'>
              <%end%>
                  <span data-feather="home"></span>
                  Dashboard<span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= user_job_apps_path(current_user.id) %>">
                  <span data-feather="file"></span>
                  Job Apps
                </a>
              </li>
                      <% if client_logged_in? || hro_logged_in? %>
        <li class="nav-item">
          <a class="nav-link active" href="<%= user_jobs_path(current_user.id)%>">
            <span data-feather="folder"></span>
            
              Jobs
            
          </a>
        </li>
        <% end %>
               <% if hro_logged_in? %>
                <li class="nav-item">
                  <a class="nav-link" href="<%= clientes_path(current_hro.id)%>">
                    <span data-feather="users"></span>
                    Clients
                  </a>
                </li>
              <%end%>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="bar-chart-2"></span>
                  Reports
                </a>
              </li>
              
            </ul>


            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2"><%= @client.name + ' ' + @client.last_name + ' ' %>Job details</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                This week
              </button>
            </div>
          </div>
          <div>
      <div><h3><%= @job.position%></h3></div>
      <%= @job.description%>
      <div>
      <%= @job.requirements%>
      </div>
      </div>
      <% if current_user && current_user.role == "Trabajador" && @job.job_apps.where(user_id: current_worker.id).length == 0%>
            <div>
                <%=button_to "Apply", user_job_apps_path(current_user), method: :post, params: {job_id: @job.id}, class: "btn btn-primary mt-3" %>
            </div>
      <%elsif current_user && current_user.role == "Trabajador" %>
      <br>
      <hr/>
        <div><h5>You have already applied to this job.</h5></div>
      <% end %>
          </main>
    </div>


<!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>


    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

app/views/jobs/showInfo.js.erb
$(".jobdetails").html("<%= escape_javascript(render partial: 'jobs/info', locals: { job: @job } ) %>");